### ISSUE TITLE
Update peerDependencies to router5@5.x.x

### ISSUE THREAD

**Issue by thupi** [LeonardoGentile/react-mobx-router5#1]
Hey,

While trying to update router5 i discovered that this package requires router5@4.x.x :-) It would be really great if the package could support router5@5.x.x as well :-) !

**Comment by LeonardoGentile** [comment]
The version 4.0.0 should work now with peerDependencies:

```
"mobx-router5": "^3.0.0",
"router5": "^5.0.0"
```
Let me know if you have any trouble

**Comment by thupi** [comment]
@LeonardoGentile Thanks for the quick update :-) ! I will try to update the dependencies :-)
