### ISSUE TITLE
BaseLink onClick prop should not require router

### ISSUE THREAD

**Issue by pzmosquito** [LeonardoGentile/react-mobx-router5#10]
according to the documentation, the `BaseLink` component should not require `router` or `routerStore` if `onClick` prop is passed in. It's giving error `this.router is null` on Firefox and `Uncaught TypeError: Cannot read property 'navigate' of null` on Chrome

**Comment by LeonardoGentile** [comment]
Hello, I'll take a look. 
Could you create a jsbin or similar to reproduce the problem?

**Comment by pzmosquito** [comment]
https://stackblitz.com/edit/pz-react-playground

**Comment by LeonardoGentile** [comment]
Thanks, in your event handler you should prevent the default browser action:

```
const TestBaseLink = () => {
  const handleClick = (e) => {
    e.preventDefault()
    console.log("test");

  };

  return <BaseLink onClick={handleClick}>test baselink</BaseLink>;
};

render(<TestBaseLink />, document.getElementById("root"));
```

**Comment by pzmosquito** [comment]
Uhhh... How on earth did I forget about that... Thanks for pointing it out.
