### ISSUE TITLE
react 16 support

### ISSUE THREAD

**Issue by pzmosquito** [LeonardoGentile/react-mobx-router5#3]
peer dependency requires react@^15.0.0, it'll be nice to support react 16 :)

**Comment by LeonardoGentile** [comment]
Hello, I've release Version [5.0.0](https://github.com/LeonardoGentile/react-mobx-router5/releases/tag/v5.0.0) that now supports React 16.
Now RouteView is wrapped with Error Boundary, please check the Readme [section](https://github.com/LeonardoGentile/react-mobx-router5#routeview---component).

Let me know if you find any bug with while using this new release
